version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki
      - jaeger
